server:
  port: 8080

# mysql
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=PRC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver